### ISSUE TITLE
hyakko-0.6.6 is incompatible with recent versions of pandoc

### ISSUE THREAD

**Issue by peti** [sourrust/hyakko#2]
http://hydra.cryp.to/build/915326/log/raw

**Comment by sourrust** [comment]
Theres a reason for the pandoc limit of `pandoc == 1.13.*`. It seems you are forcing all dependency limits to be lifted and that is what caused this error. I see this in the log you linked:

`Run jailbreak-cabal to lift version restrictions on build inputs.`

And right now hyakko requires `1.13.*` no more. However I do what to get to updating dependencies soon but this is not a bug as you, or this `jailbreak-cabal`, is purposefully ignoring dependency limits.

**Comment by peti** [comment]
I removed this package from the NixOS distribution since we cannot build it and apparently you don't consider that an issue that might be worth engaging in communication over.

**Comment by sourrust** [comment]
Like I said in the comment closing this, I do want to update hyakko's dependences. However, seeing as you are using something that purposefully removes version limit off of the cabal file it isn't a surprise you get build errors. If you used the regular cabal there is no issue because it follows the dependencies described in the package.

**Comment by peti** [comment]
We maintain over 8000 Haskell packages in Nix, and the issue tracker is the only way to keep track of outstanding changes that require a modification of our setup. Normally, people close such an issue when it is *solved* and that event pings me to update the package and retry the build. Unfortunately, you break that communication mechanism because you worry more about fucking nomenclature than about supporting a user. So I won't package your software.

**Comment by sourrust** [comment]
That's fine. It's not about supporting users because, like I said once again, I was going to update my dependences any and have. If you want to get snappy because your build system forces cabal to not adhere to something that was specified in a package, that's your call. However, I'm not pushing this "fix" to hackage until tomorrow.
